description: example job

target:
  service: sing
  name: msrresrchvc
  workspace_name: gcrllama2ws

code:
  local_dir: /home/t-smantena/deep-fMRI-dataset # path to your code on local machine

environment:
  image: amlt-sing/acpt-2.3.1-py3.10-cuda12.1
  setup:
    # working directory is local_dir under code above
    - pip install -r requirements.txt --user # install requirements from file
    # - pip install . # install a package from the local directory

storage:
  data:
    storage_account_name: internblobdl
    container_name: t-smantena
    mount_dir: /blob_data # path to mount the blob on the remote machine

jobs:
  - name: save_sub1_resp
    process_count_per_node: 1
    sku: G1-A100
    command:
      - python3 encoding/encoding_PResp.py --subject UTS01
  - name: save_sub2_resp
    process_count_per_node: 1
    sku: G1-A100
    command:
      - python3 encoding/encoding_PResp.py --subject UTS03
  - name: save_sub3_resp
    process_count_per_node: 1
    sku: G1-A100
    command:
      - python3 encoding/encoding_PResp.py --subject UTS03
